name: Deploy to Kubernetes using Helm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .kube directory
        run: mkdir -p $HOME/.kube

      - name: Set up Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Helm Deploy
        run: |
          helm upgrade --install ${{ secrets.HELM_RELEASE_NAME }} ./charts/simple-app --namespace ${{ secrets.NAMESPACE }} --create-namespace


