name: Deploy to Kubernetes using Helm

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 --decode > $HOME/.kube/config

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0 # Optional: specify a Helm version

      - name: Update Helm dependencies (if needed)
        run: helm dependency update ./charts/simple-app

      - name: Deploy with Helm
        run: |
          helm upgrade --install ${{ secrets.HELM_RELEASE_NAME }} ./charts/simple-app \
            --namespace ${{ secrets.NAMESPACE }} \
            --create-namespace \
            -f ./charts/simple-app/values.yaml
